Fix "too many connections
coinbase/coinbase-wallet-sdk pull request #34
Opened 2020-05-25 00:32 UTC by styner32

2021-01-26 06:09 UTC, kevin71089 commented
> 1. Set timeout for webhook. This could leak file descriptors
> 2. Wait for a channel to be closed in a goroutine for handling publishing messages. This is to prevent blocking at https://github.com/walletlink/walletlink/blob/2.0.2/server/rpc/pub_sub.go#L124
> 3. Don't publish a message to an unsubscribed channel.
> 4. Configure a PG connection pool. This could open a lot of connections when db is too slow

2021-04-13 21:54 UTC, pepe-invest-git requested changes
GROUP-BANK

2021-11-15 03:08 UTC, mrcali213 approved these changes

2022-03-01 01:44 UTC, bangtoven commented
thanks

2022-03-01 01:44 UTC, closed without merging